language: python
python:
  - "2.7"

branches:
  only:
    - feature-review

install:
  - pip install -r requirements.txt
  - pip install coveralls

env:
  - DB=sqlite

script:
  - python manage.py test --settings=MasduRestApi.settings.test

after_success:
  - coveralls
